# Generated by Django 5.0 on 2024-01-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ourservices_remove_service_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_charge',
        ),
        migrations.AddField(
            model_name='ourservices',
            name='service_charge',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
