# Generated by Django 5.0 on 2024-01-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_service_our_service_ourservices_our_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='our_service_images'),
        ),
    ]
