# Generated by Django 5.0 on 2024-01-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_ourservices_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
