# Generated by Django 5.0 on 2024-01-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_booking_address_booking_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
