# Generated by Django 5.0 on 2024-01-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='professional',
        ),
    ]
