# Generated by Django 5.0 on 2024-01-31 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ourservices'),
        ),
    ]
